"""Add songs , Charts , and more

Revision ID: c47540bb1ba3
Revises: 555eb40a023a
Create Date: 2023-06-11 16:03:08.853299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47540bb1ba3'
down_revision = '555eb40a023a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('music_brainz_identifier', sa.String(), nullable=True),
    sa.Column('spotify_id', sa.String(), nullable=True),
    sa.Column('isni_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('info_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_index(op.f('ix_songs_music_brainz_identifier'), 'songs', ['music_brainz_identifier'], unique=False)
    op.create_index(op.f('ix_songs_spotify_id'), 'songs', ['spotify_id'], unique=False)
    op.create_table('charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('chart', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charts_id'), 'charts', ['id'], unique=False)
    op.create_index(op.f('ix_charts_song_id'), 'charts', ['song_id'], unique=False)
    op.create_index(op.f('ix_charts_user_id'), 'charts', ['user_id'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('facebook_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_visibility', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_visibility')
    op.drop_column('users', 'facebook_id')
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_charts_user_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_song_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_id'), table_name='charts')
    op.drop_table('charts')
    op.drop_index(op.f('ix_songs_spotify_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_music_brainz_identifier'), table_name='songs')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###
