"""Rename thumbnail in user to avatar

Revision ID: e7a6a46f40ad
Revises: 186f44585b7e
Create Date: 2023-06-18 15:59:26.122541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7a6a46f40ad'
down_revision = '186f44585b7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('thumbnail', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
