"""fix datetime for article

Revision ID: f4bde4daa063
Revises: ac8f834cea87
Create Date: 2023-05-25 15:10:05.764839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bde4daa063'
down_revision = 'ac8f834cea87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'article_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('article_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
